In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [3]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5
0   Atharv  19.0    Mhow     96        72.0         NaN
1   Atharv  19.0    Mhow     96        72.0         NaN
2     Aman   NaN  Indore     78        85.0         NaN
3     Riya  20.0  Bhopal     92        95.0         NaN
4    Kunal  18.0  Indore     67        80.0         NaN
5    Sneha  19.0  Ujjain     88         NaN         NaN
6    Arjun  17.0  Bhopal     74        70.0         NaN
7    Priya  20.0  Indore     95        98.0         NaN
8     Neha  42.0  Bhopal     81        88.0         NaN
9    Rohit  18.0  Ujjain     60        65.0         NaN
10    Neha  42.0  Bhopal     81        88.0         NaN
11   Vikas  10.0     NaN     73        75.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [4]:
df.shape

(13, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        13 non-null     str
 1   Age         12 non-null     float64
 2   City        12 non-null     str
 3   marks       13 non-null     int64
 4   Attendance  12 non-null     float64
 5   Unnamed: 5  0 non-null      float64
dtypes: float64(3), int64(1), str(2)
memory usage: 756.0 bytes

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('students.csv')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        13 non-null     str
 1   Age         12 non-null     float64
 2   City        12 non-null     str
 3   marks       13 non-null     int64
 4   Attendance  12 non-null     float64
 5   Unnamed: 5  0 non-null      float64
dtypes: float64(3), int64(1), str(2)
memory usage: 756.0 bytes

In [9]:
df.tail()

      Name   Age    City  marks  Attendance  Unnamed: 5
8     Neha  42.0  Bhopal     81        88.0         NaN
9    Rohit  18.0  Ujjain     60        65.0         NaN
10    Neha  42.0  Bhopal     81        88.0         NaN
11   Vikas  10.0     NaN     73        75.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [10]:
df.head()

     Name   Age    City  marks  Attendance  Unnamed: 5
0  Atharv  19.0    Mhow     96        72.0         NaN
1  Atharv  19.0    Mhow     96        72.0         NaN
2    Aman   NaN  Indore     78        85.0         NaN
3    Riya  20.0  Bhopal     92        95.0         NaN
4   Kunal  18.0  Indore     67        80.0         NaN

In [11]:
df.columns

Index(['Name', 'Age', 'City', 'marks', 'Attendance', 'Unnamed: 5'], dtype='str')

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('students.csv')

In [14]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5
0   Atharv  19.0    Mhow     96        72.0         NaN
1   Atharv  19.0    Mhow     96        72.0         NaN
2     Aman   NaN  Indore     78        85.0         NaN
3     Riya  20.0  Bhopal     92        95.0         NaN
4    Kunal  18.0  Indore     67        80.0         NaN
5    Sneha  19.0  Ujjain     88         NaN         NaN
6    Arjun  17.0  Bhopal     74        70.0         NaN
7    Priya  20.0  Indore     95        98.0         NaN
8     Neha  42.0  Bhopal     81        88.0         NaN
9    Rohit  18.0  Ujjain     60        65.0         NaN
10    Neha  42.0  Bhopal     81        88.0         NaN
11   Vikas  10.0     NaN     73        75.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [15]:
df.head()

     Name   Age    City  marks  Attendance  Unnamed: 5
0  Atharv  19.0    Mhow     96        72.0         NaN
1  Atharv  19.0    Mhow     96        72.0         NaN
2    Aman   NaN  Indore     78        85.0         NaN
3    Riya  20.0  Bhopal     92        95.0         NaN
4   Kunal  18.0  Indore     67        80.0         NaN

In [16]:
df.tail()

      Name   Age    City  marks  Attendance  Unnamed: 5
8     Neha  42.0  Bhopal     81        88.0         NaN
9    Rohit  18.0  Ujjain     60        65.0         NaN
10    Neha  42.0  Bhopal     81        88.0         NaN
11   Vikas  10.0     NaN     73        75.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [17]:
df.columns

Index(['Name', 'Age', 'City', 'marks', 'Attendance', 'Unnamed: 5'], dtype='str')

In [18]:
df.shape

(13, 6)

In [19]:
df['marks']

0     96
1     96
2     78
3     92
4     67
5     88
6     74
7     95
8     81
9     60
10    81
11    73
12    89
Name: marks, dtype: int64

In [20]:
type(df.marks)

pandas.Series

In [21]:
type(df['marks'])

pandas.Series

In [22]:
df.iloc[[0, 3], [1]]

    Age
0  19.0
3  20.0

In [23]:
df.loc[[0, 3], ['marks']]

   marks
0     96
3     92

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('students.csv')

In [26]:
df['mean'] = df['marks'].sum() / df['marks'].max()

In [27]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5       mean
0   Atharv  19.0    Mhow     96        72.0         NaN  11.145833
1   Atharv  19.0    Mhow     96        72.0         NaN  11.145833
2     Aman   NaN  Indore     78        85.0         NaN  11.145833
3     Riya  20.0  Bhopal     92        95.0         NaN  11.145833
4    Kunal  18.0  Indore     67        80.0         NaN  11.145833
5    Sneha  19.0  Ujjain     88         NaN         NaN  11.145833
6    Arjun  17.0  Bhopal     74        70.0         NaN  11.145833
7    Priya  20.0  Indore     95        98.0         NaN  11.145833
8     Neha  42.0  Bhopal     81        88.0         NaN  11.145833
9    Rohit  18.0  Ujjain     60        65.0         NaN  11.145833
10    Neha  42.0  Bhopal     81        88.0         NaN  11.145833
11   Vikas  10.0     NaN     73        75.0         NaN  11.145833
12  Anjali  21.0  Ujjain     89        92.0         NaN  11.145833

In [28]:
df['marks'].mean()

np.float64(82.3076923076923)

In [29]:
df['marks'].max()

np.int64(96)

In [30]:
df.loc[df['marks'] > 75, 'Status'] = 'Pass'
df.loc[df['marks'] < 75, 'Status'] = 'Fail'

In [31]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5       mean Status
0   Atharv  19.0    Mhow     96        72.0         NaN  11.145833   Pass
1   Atharv  19.0    Mhow     96        72.0         NaN  11.145833   Pass
2     Aman   NaN  Indore     78        85.0         NaN  11.145833   Pass
3     Riya  20.0  Bhopal     92        95.0         NaN  11.145833   Pass
4    Kunal  18.0  Indore     67        80.0         NaN  11.145833   Fail
5    Sneha  19.0  Ujjain     88         NaN         NaN  11.145833   Pass
6    Arjun  17.0  Bhopal     74        70.0         NaN  11.145833   Fail
7    Priya  20.0  Indore     95        98.0         NaN  11.145833   Pass
8     Neha  42.0  Bhopal     81        88.0         NaN  11.145833   Pass
9    Rohit  18.0  Ujjain     60        65.0         NaN  11.145833   Fail
10    Neha  42.0  Bhopal     81        88.0         NaN  11.145833   Pass
11   Vikas  10.0     NaN     73        75.0         NaN  11.145833   Fail
12  Anjali  21.0  Ujjain     89        92.0         NaN  11.145833   Pass

In [32]:
df.shape

(13, 8)

In [33]:
nulll = df['marks'].isnull()

In [34]:
nulll

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
Name: marks, dtype: bool

In [35]:
df[nulll]

Empty DataFrame
Columns: [Name, Age, City, marks, Attendance, Unnamed: 5, mean, Status]
Index: []

In [36]:
df = pd.read_csv('Students.csv')

In [37]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5
0   Atharv  19.0    Mhow     96        72.0         NaN
1   Atharv  19.0    Mhow     96        72.0         NaN
2     Aman   NaN  Indore     78        85.0         NaN
3     Riya  20.0  Bhopal     92        95.0         NaN
4    Kunal  18.0  Indore     67        80.0         NaN
5    Sneha  19.0  Ujjain     88         NaN         NaN
6    Arjun  17.0  Bhopal     74        70.0         NaN
7    Priya  20.0  Indore     95        98.0         NaN
8     Neha  42.0  Bhopal     81        88.0         NaN
9    Rohit  18.0  Ujjain     60        65.0         NaN
10    Neha  42.0  Bhopal     81        88.0         NaN
11   Vikas  10.0     NaN     73        75.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [38]:
topper = df['marks'] >= 85
loser = df['marks'] < 75

In [39]:
df[topper]

      Name   Age    City  marks  Attendance  Unnamed: 5
0   Atharv  19.0    Mhow     96        72.0         NaN
1   Atharv  19.0    Mhow     96        72.0         NaN
3     Riya  20.0  Bhopal     92        95.0         NaN
5    Sneha  19.0  Ujjain     88         NaN         NaN
7    Priya  20.0  Indore     95        98.0         NaN
12  Anjali  21.0  Ujjain     89        92.0         NaN

In [40]:
df[loser]

     Name   Age    City  marks  Attendance  Unnamed: 5
4   Kunal  18.0  Indore     67        80.0         NaN
6   Arjun  17.0  Bhopal     74        70.0         NaN
9   Rohit  18.0  Ujjain     60        65.0         NaN
11  Vikas  10.0     NaN     73        75.0         NaN

In [41]:
city = (df['City'] == 'Indore') & (df['Attendance'] >= 75)

In [42]:
df[city]

    Name   Age    City  marks  Attendance  Unnamed: 5
2   Aman   NaN  Indore     78        85.0         NaN
4  Kunal  18.0  Indore     67        80.0         NaN
7  Priya  20.0  Indore     95        98.0         NaN

In [43]:
df['marks'].max()

np.int64(96)

In [44]:
df.groupby("City")["marks"].mean()

City
Bhopal    82.0
Indore    80.0
Mhow      96.0
Ujjain    79.0
Name: marks, dtype: float64

In [45]:
df.loc[df['marks'] > 75, 'Status'] = 'Pass'
df.loc[df['marks'] < 75, 'Status'] = 'Improve'

In [46]:
df

      Name   Age    City  marks  Attendance  Unnamed: 5   Status
0   Atharv  19.0    Mhow     96        72.0         NaN     Pass
1   Atharv  19.0    Mhow     96        72.0         NaN     Pass
2     Aman   NaN  Indore     78        85.0         NaN     Pass
3     Riya  20.0  Bhopal     92        95.0         NaN     Pass
4    Kunal  18.0  Indore     67        80.0         NaN  Improve
5    Sneha  19.0  Ujjain     88         NaN         NaN     Pass
6    Arjun  17.0  Bhopal     74        70.0         NaN  Improve
7    Priya  20.0  Indore     95        98.0         NaN     Pass
8     Neha  42.0  Bhopal     81        88.0         NaN     Pass
9    Rohit  18.0  Ujjain     60        65.0         NaN  Improve
10    Neha  42.0  Bhopal     81        88.0         NaN     Pass
11   Vikas  10.0     NaN     73        75.0         NaN  Improve
12  Anjali  21.0  Ujjain     89        92.0         NaN     Pass

In [47]:
df['marks'].mean()

np.float64(82.3076923076923)

In [48]:
df.isnull().sum()

Name           0
Age            1
City           1
marks          0
Attendance     1
Unnamed: 5    13
Status         0
dtype: int64

In [49]:
import pandas as pd
df = pd.read_csv('students.csv')
df.loc[df['Age'] >= 20, 'age_group'] = 'Adult'
df.loc[df['Age'] < 20, 'age_group'] = 'Teen'
df.loc[df['marks'] >= 80, 'marks_band'] = 'High'
df.loc[(df['marks'] < 80) & (df['marks'] > 60), 'marks_band'] = 'Medium'
df.loc[df['marks'] <= 60, 'marks_band'] = 'Low'
df.loc[(df['marks_band'] == 'High') & (df['age_group'] == 'Teen'), 'Student_profile'] = 'Brilliant!'
df.loc[(df['marks_band'] == 'High') & (df['age_group'] == 'Adult'), 'Student_profile'] = 'Good'
df.loc[(df['marks_band'] == 'Medium'), 'Student_profile'] = 'Workable'
df.loc[(df['marks_band'] == 'Low'), 'Student_profile'] = 'Loser'

In [50]:
df.loc[0, 'Student_profile']

'Brilliant!'

In [51]:
df

,Name,Age,City,marks,Attendance,Unnamed: 5,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
1,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,NaN,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,NaN,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,NaN,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,NaN,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,NaN,Teen,Low,Loser
10,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
11,Vikas,10.0,NaN,73,75.0,NaN,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,NaN,Adult,High,Good

In [52]:
gud = df['Student_profile'].str.contains('Brilliant!')

In [53]:
df.loc[gud, 'Student_profile']

0    Brilliant!
1    Brilliant!
5    Brilliant!
Name: Student_profile, dtype: str

In [54]:
df.describe()

             Age      marks  Attendance  Unnamed: 5
count  12.000000  13.000000   12.000000         0.0
mean   22.083333  82.307692   81.666667         NaN
std     9.709024  11.607358   10.832051         NaN
min    10.000000  60.000000   65.000000         NaN
25%    18.000000  74.000000   72.000000         NaN
50%    19.000000  81.000000   82.500000         NaN
75%    20.250000  92.000000   89.000000         NaN
max    42.000000  96.000000   98.000000         NaN

In [55]:
df['Student_profile'].value_counts()

Student_profile
Good          5
Workable      4
Brilliant!    3
Loser         1
Name: count, dtype: int64

In [56]:
df['Attendance'].max()

np.float64(98.0)

In [57]:
hai = df['Attendance'] == 98
df[hai]

,Name,Age,City,marks,Attendance,Unnamed: 5,age_group,marks_band,Student_profile
7,Priya,20.0,Indore,95,98.0,NaN,Adult,High,Good

In [58]:
df['Age'].sort_values()

11    10.0
6     17.0
9     18.0
4     18.0
5     19.0
0     19.0
1     19.0
3     20.0
7     20.0
12    21.0
8     42.0
10    42.0
2      NaN
Name: Age, dtype: float64

In [59]:
df.loc[9]

Name                Rohit
Age                  18.0
City               Ujjain
marks                  60
Attendance           65.0
Unnamed: 5            NaN
age_group            Teen
marks_band            Low
Student_profile     Loser
Name: 9, dtype: object

In [60]:
df['Age'].isnull().value_counts()

Age
False    12
True      1
Name: count, dtype: int64

In [61]:
df['Age'].min()

np.float64(10.0)

In [62]:
df.isnull().sum()

Name                0
Age                 1
City                1
marks               0
Attendance          1
Unnamed: 5         13
age_group           1
marks_band          0
Student_profile     0
dtype: int64

In [63]:
df['Age'].fillna(df['Age'].median())

0     19.0
1     19.0
2     19.0
3     20.0
4     18.0
5     19.0
6     17.0
7     20.0
8     42.0
9     18.0
10    42.0
11    10.0
12    21.0
Name: Age, dtype: float64

In [64]:
df

,Name,Age,City,marks,Attendance,Unnamed: 5,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
1,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,NaN,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,NaN,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,NaN,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,NaN,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,NaN,Teen,Low,Loser
10,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
11,Vikas,10.0,NaN,73,75.0,NaN,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,NaN,Adult,High,Good

In [65]:
grp = df.groupby('City')['marks']

In [66]:
df.groupby('City')['marks'].min()

City
Bhopal    74
Indore    67
Mhow      96
Ujjain    60
Name: marks, dtype: int64

In [67]:
grp.get_group('Ujjain').sort_values()

9     60
5     88
12    89
Name: marks, dtype: int64

In [68]:
df.loc[7]

Name                Priya
Age                  20.0
City               Indore
marks                  95
Attendance           98.0
Unnamed: 5            NaN
age_group           Adult
marks_band           High
Student_profile      Good
Name: 7, dtype: object

In [69]:
df.groupby('City')['Name'].count()

City
Bhopal    4
Indore    3
Mhow      2
Ujjain    3
Name: Name, dtype: int64

In [70]:
df.groupby('City')['marks'].describe()

        count  mean        std   min    25%   50%    75%   max
City
Bhopal    4.0  82.0   7.438638  74.0  79.25  81.0  83.75  92.0
Indore    3.0  80.0  14.106736  67.0  72.50  78.0  86.50  95.0
Mhow      2.0  96.0   0.000000  96.0  96.00  96.0  96.00  96.0
Ujjain    3.0  79.0  16.462078  60.0  74.00  88.0  88.50  89.0

In [71]:
df.groupby('City')['marks_band'].value_counts()

City    marks_band
Bhopal  High          3
        Medium        1
Indore  Medium        2
        High          1
Mhow    High          2
Ujjain  High          2
        Low           1
Name: count, dtype: int64

In [72]:
df.describe()

             Age      marks  Attendance  Unnamed: 5
count  12.000000  13.000000   12.000000         0.0
mean   22.083333  82.307692   81.666667         NaN
std     9.709024  11.607358   10.832051         NaN
min    10.000000  60.000000   65.000000         NaN
25%    18.000000  74.000000   72.000000         NaN
50%    19.000000  81.000000   82.500000         NaN
75%    20.250000  92.000000   89.000000         NaN
max    42.000000  96.000000   98.000000         NaN

In [73]:
df

,Name,Age,City,marks,Attendance,Unnamed: 5,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
1,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,NaN,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,NaN,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,NaN,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,NaN,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,NaN,Teen,Low,Loser
10,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
11,Vikas,10.0,NaN,73,75.0,NaN,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,NaN,Adult,High,Good

In [74]:
df.dropna(axis='columns', how='all', inplace=True)

In [75]:
df.drop_duplicates(inplace=True)

In [76]:
df['marks'].sort_values(ascending=False)

0     96
7     95
3     92
12    89
5     88
8     81
2     78
6     74
11    73
4     67
9     60
Name: marks, dtype: int64

In [77]:
df

,Name,Age,City,marks,Attendance,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,Teen,Low,Loser
11,Vikas,10.0,NaN,73,75.0,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,Adult,High,Good

In [78]:
import numpy as np

In [79]:
x = [2, 4, 5, 3, 6]
y = np.array(x)

In [80]:
print(y)
print(type(y))

[2 4 5 3 6]
<class 'numpy.ndarray'>

In [81]:
import numpy as np
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.isnull().sum()
df.shape

(18, 7)

In [82]:
df.isnull().sum()

name           0
age            0
marks          0
study_hours    0
city           0
sleep_hours    0
attendance     0
dtype: int64

In [83]:
df.shape

(18, 7)

In [84]:
cleandf = df.drop_duplicates()

In [85]:
cleandf.isnull().sum()

name           0
age            0
marks          0
study_hours    0
city           0
sleep_hours    0
attendance     0
dtype: int64

In [86]:
cleandf = df[df["marks"].notnull()]

In [87]:
df["marks"].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
Name: marks, dtype: bool

In [88]:
cleandf.loc[cleandf['marks'] >= 80, 'Performance'] = 'High'
cleandf.loc[(cleandf['marks'] < 80) | (cleandf['marks'] >= 60), 'Performance'] = 'Medium'
cleandf.loc[cleandf['marks'] < 60, 'Performance'] = 'Low'
cleandf['marks'] = cleandf['marks'].fillna(cleandf['marks'].median())

In [89]:
import numpy as np
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.isnull().sum()

name           0
age            0
marks          0
study_hours    0
city           0
sleep_hours    0
attendance     0
dtype: int64

In [90]:
cleandf = df.drop_duplicates()

In [91]:
cleandf['marks'] = cleandf['marks'].fillna(cleandf['marks'].median())

In [92]:
cleandf.loc[cleandf['marks'] > 80, 'Performance'] = 'High'
cleandf.loc[(cleandf['marks'] < 80) & (cleandf['marks'] > 60), 'Performance'] = 'Medium'
cleandf.loc[cleandf['marks'] < 60, 'Performance'] = 'Low'

In [93]:
cleandf['age'] = cleandf['age'].fillna(cleandf['age'].median())
cleandf['study_hours'] = cleandf['study_hours'].fillna(cleandf['study_hours'].median())

In [94]:
cleandf = cleandf.dropna(subset=['city'])

In [95]:
cleandf.reset_index(inplace = True)

In [96]:
cleandf.loc[cleandf['study_hours'] >= 5, 'Study Category'] = 'Serious'
cleandf.loc[cleandf['study_hours'] < 5, 'Study Category'] = 'Casual'

In [97]:
cleandf.loc[cleandf['Performance'].str.contains('High') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Good'
cleandf.loc[cleandf['Performance'].str.contains('High') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Brilliant'
cleandf.loc[cleandf['Performance'].str.contains('Low') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Gotta focus'
cleandf.loc[cleandf['Performance'].str.contains('Low') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Study Beta'
cleandf.loc[cleandf['Performance'].str.contains('Medium') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Improve focus'
cleandf.loc[cleandf['Performance'].str.contains('Medium') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Study more'

In [98]:
cleandf

,index,name,age,marks,study_hours,city,sleep_hours,attendance,Performance,Study Category,Overall
0,0,Aarav Sharma,19,85,6,Delhi,8,90,High,Serious,Good
1,1,Priya Singh,20,92,8,Mumbai,7,85,High,Serious,Good
2,2,Rohan Gupta,18,74,4,Bangalore,6,80,Medium,Casual,Study more
3,3,Sneha Patel,21,68,5,Bangalore,9,75,Medium,Serious,Improve focus
4,4,Vikram Das,19,40,3,Kolkata,7,70,Low,Casual,Study Beta
5,5,Ananya Iyer,20,88,7,Chennai,8,95,High,Serious,Good
6,7,Kabir Khan,22,95,9,Delhi,8,90,High,Serious,Good
7,8,Meera Nair,19,55,5,Pune,7,85,Low,Serious,Gotta focus
8,9,Arjun Reddy,20,79,6,Hyderabad,8,85,Medium,Serious,Improve focus
9,10,Ishan Verma,21,82,5,Ahmedabad,9,80,High,Serious,Good
10,11,Kavita Rao,21,45,2,Bangalore,6,75,Low,Casual,Study Beta
11,12,Sahil Mehta,19,90,7,Mumbai,8,90,High,Serious,Good
12,14,Riya Das,18,62,4,Kolkata,7,75,Medium,Casual,Study more
13,15,Amit Shah,20,80,6,Delhi,8,90,NaN,Serious,NaN
14,16,Pooja Joshi,19,71,3,Pune,7,80,Medium,Casual,Study more

In [99]:
cleandf.groupby('city')['marks'].mean()

city
Ahmedabad    82.000000
Bangalore    62.333333
Chennai      88.000000
Delhi        86.666667
Hyderabad    79.000000
Kolkata      51.000000
Mumbai       91.000000
Pune         63.000000
Name: marks, dtype: float64

In [100]:
cleandf.groupby('Performance')['marks'].mean()

Performance
High      88.666667
Low       46.666667
Medium    70.800000
Name: marks, dtype: float64

In [101]:
array = cleandf['marks'].astype(float).to_numpy()

In [102]:
print(array)

[85. 92. 74. 68. 40. 88. 95. 55. 79. 82. 45. 90. 62. 80. 71.]

In [103]:
array.mean()

np.float64(73.73333333333333)

In [104]:
array.max()

np.float64(95.0)

In [105]:
array.min()

np.float64(40.0)

In [106]:
gudarray = 1/array.max() * array

In [107]:
print(gudarray)

[0.89473684 0.96842105 0.77894737 0.71578947 0.42105263 0.92631579
 1.         0.57894737 0.83157895 0.86315789 0.47368421 0.94736842
 0.65263158 0.84210526 0.74736842]

In [108]:
cleandf['marks'].sort_values(ascending = False).head()

6     95
1     92
11    90
5     88
0     85
Name: marks, dtype: int64

In [109]:
df[["study_hours", "marks"]].corr()

             study_hours     marks
study_hours     1.000000  0.852321
marks           0.852321  1.000000