In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [4]:
df

     name  marks
0    Aman     78
1    Riya     92
2   Rahul     60
3    Neha     85
4   Sahil     55
5    Tina     88
6  Vikram     73
7   Arjun     95
8    Maya     67
9    Sara     80

In [6]:
df.shape

(10, 2)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   marks   10 non-null     int64
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('students.csv')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   marks   10 non-null     int64
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [10]:
df.tail()

     name  marks
5    Tina     88
6  Vikram     73
7   Arjun     95
8    Maya     67
9    Sara     80

In [11]:
df.head()

    name  marks
0   Aman     78
1   Riya     92
2  Rahul     60
3   Neha     85
4  Sahil     55

In [12]:
df.columns

Index(['name', 'marks'], dtype='str')

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [3]:
df

     name  marks
0    Aman     78
1    Riya     92
2   Rahul     60
3    Neha     85
4   Sahil     55
5    Tina     88
6  Vikram     73
7   Arjun     95
8    Maya     67
9    Sara     80

In [4]:
df.head()

    name  marks
0   Aman     78
1   Riya     92
2  Rahul     60
3   Neha     85
4  Sahil     55

In [5]:
df.tail()

     name  marks
5    Tina     88
6  Vikram     73
7   Arjun     95
8    Maya     67
9    Sara     80

In [6]:
df.columns

Index(['name', 'marks'], dtype='str')

In [9]:
df.shape

(10, 2)

In [10]:
df.marks

0    78
1    92
2    60
3    85
4    55
5    88
6    73
7    95
8    67
9    80
Name: marks, dtype: int64

In [11]:
df['marks']

0    78
1    92
2    60
3    85
4    55
5    88
6    73
7    95
8    67
9    80
Name: marks, dtype: int64

In [12]:
type(df.marks)

pandas.Series

In [13]:
type(df['marks'])

pandas.Series

In [19]:
df.iloc[[0, 3], [1]]

   marks
0     78
3     85

In [18]:
df.loc[[0, 3], ['marks']]

   marks
0     78
3     85

In [9]:
import pandas as pd

In [7]:
df = pd.read_csv('students.csv')

In [27]:
df['mean'] = df['marks'].sum() / df['marks'].max()

In [28]:
df

     name  marks      mean  sum
0    Aman     78  7.136842  773
1    Riya     92  7.136842  773
2   Rahul     60  7.136842  773
3    Neha     85  7.136842  773
4   Sahil     55  7.136842  773
5    Tina     88  7.136842  773
6  Vikram     73  7.136842  773
7   Arjun     95  7.136842  773
8    Maya     67  7.136842  773
9    Sara     80  7.136842  773

In [23]:
df['marks'].mean()

np.float64(77.3)

In [29]:
df['marks'].max()

np.int64(95)

In [34]:
df.drop(columns=['mean', 'sum'])

     name  marks
0    Aman     78
1    Riya     92
2   Rahul     60
3    Neha     85
4   Sahil     55
5    Tina     88
6  Vikram     73
7   Arjun     95
8    Maya     67
9    Sara     80

In [40]:
df.loc[df['marks'] > 75, 'Status'] = 'Pass'
df.loc[df['marks'] < 75, 'Status'] = 'Fail'

In [44]:
df.drop(columns=['status', 'sum', 'mean'])

     name  marks Status
0    Aman     78   Pass
1    Riya     92   Pass
2   Rahul     60   Fail
3    Neha     85   Pass
4   Sahil     55   Fail
5    Tina     88   Pass
6  Vikram     73   Fail
7   Arjun     95   Pass
8    Maya     67   Fail
9    Sara     80   Pass

In [6]:
df

    name  marks   age
0   Aman   78.0  19.0
1   Riya    NaN  20.0
2  Rahul   60.0   NaN
3   Neha   85.0  21.0
4  Kiran    NaN  18.0

In [3]:
df.shape

(5, 3)

In [31]:
nulll = df['marks'].isnull()

In [72]:
nulll

0    False
1     True
2    False
3    False
4     True
Name: marks, dtype: bool

In [34]:
df[nulll]

    name  marks   age
1   Riya    NaN  20.0
4  Kiran    NaN  18.0

In [35]:
df = pd.read_csv('Students.csv')

In [36]:
df

      Name  Age    City  Marks  Attendance
0   Atharv   19    Mhow     96          72
1     Aman   15  Indore     78          85
2     Riya   20  Bhopal     92          95
3    Kunal   18  Indore     67          80
4    Sneha   19  Ujjain     88          90
5    Arjun   17  Bhopal     74          70
6    Priya   20  Indore     95          98
7    Rohit   18  Ujjain     60          65
8     Neha   42  Bhopal     81          88
9    Vikas   10  Indore     73          75
10  Anjali   21  Ujjain     89          92

In [41]:
topper = df['Marks'] >= 85
loser = df['Marks'] < 75

In [47]:
df[topper]

      Name  Age    City  Marks  Attendance
0   Atharv   19    Mhow     96          72
2     Riya   20  Bhopal     92          95
4    Sneha   19  Ujjain     88          90
6    Priya   20  Indore     95          98
10  Anjali   21  Ujjain     89          92

In [48]:
df[loser]

    Name  Age    City  Marks  Attendance
3  Kunal   18  Indore     67          80
5  Arjun   17  Bhopal     74          70
7  Rohit   18  Ujjain     60          65
9  Vikas   10  Indore     73          75

In [65]:
city = (df['City'] == 'Indore') & (df['Attendance'] >= 75)

In [66]:
df[city]

    Name  Age    City  Marks  Attendance
1   Aman   15  Indore     78          85
3  Kunal   18  Indore     67          80
6  Priya   20  Indore     95          98
9  Vikas   10  Indore     73          75

In [67]:
df['Marks'].max()

np.int64(96)

In [68]:
df.groupby("City")["Marks"].mean()

City
Bhopal    82.333333
Indore    78.250000
Mhow      96.000000
Ujjain    79.000000
Name: Marks, dtype: float64

In [24]:
df.loc[df['Marks'] > 75, 'Status'] = 'Pass'
df.loc[df['Marks'] < 75, 'Status'] = 'Improve'

In [25]:
df

      Name  Age    City  Marks  Attendance   Status
0   Atharv   19    Mhow     96          72     Pass
1     Aman   15  Indore     78          85     Pass
2     Riya   20  Bhopal     92          95     Pass
3    Kunal   18  Indore     67          80  Improve
4    Sneha   19  Ujjain     88          90     Pass
5    Arjun   17  Bhopal     74          70  Improve
6    Priya   20  Indore     95          98     Pass
7    Rohit   18  Ujjain     60          65  Improve
8     Neha   42  Bhopal     81          88     Pass
9    Vikas   10  Indore     73          75  Improve
10  Anjali   21  Ujjain     89          92     Pass

In [26]:
df['Marks'].mean()

np.float64(81.18181818181819)

In [32]:
df.isnull().sum()

Name          0
Age           1
City          1
Marks         0
Attendance    1
dtype: int64

In [16]:
import pandas as pd
df = pd.read_csv('students.csv')
df.loc[df['Age'] >= 20, 'age_group'] = 'Adult'
df.loc[df['Age'] < 20, 'age_group'] = 'Teen'
df.loc[df['Marks'] >= 80, 'marks_band'] = 'High'
df.loc[(df['Marks'] < 80) & (df['Marks'] > 60), 'marks_band'] = 'Medium'
df.loc[df['Marks'] <= 60, 'marks_band'] = 'Low'
df.loc[(df['marks_band'] == 'High') & (df['age_group'] == 'Teen'), 'Student_profile'] = 'Brilliant!'
df.loc[(df['marks_band'] == 'High') & (df['age_group'] == 'Adult'), 'Student_profile'] = 'Good'
df.loc[(df['marks_band'] == 'Medium'), 'Student_profile'] = 'Workable'
df.loc[(df['marks_band'] == 'Low'), 'Student_profile'] = 'Loser'

In [21]:
df.loc[0, 'Student_profile']

'Brilliant!'

In [22]:
df

,Name,Age,City,Marks,Attendance,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,Teen,High,Brilliant!
1,Aman,NaN,Indore,78,85.0,NaN,Medium,Workable
2,Riya,20.0,Bhopal,92,95.0,Adult,High,Good
3,Kunal,18.0,Indore,67,80.0,Teen,Medium,Workable
4,Sneha,19.0,Ujjain,88,NaN,Teen,High,Brilliant!
5,Arjun,17.0,Bhopal,74,70.0,Teen,Medium,Workable
6,Priya,20.0,Indore,95,98.0,Adult,High,Good
7,Rohit,18.0,Ujjain,60,65.0,Teen,Low,Loser
8,Neha,42.0,Bhopal,81,88.0,Adult,High,Good
9,Vikas,10.0,NaN,73,75.0,Teen,Medium,Workable
10,Anjali,21.0,Ujjain,89,92.0,Adult,High,Good

In [39]:
gud = df['Student_profile'].str.contains('Brilliant!')

In [40]:
df.loc[gud, 'Student_profile']

0    Brilliant!
4    Brilliant!
Name: Student_profile, dtype: str

In [20]:
df.describe()

             Age      Marks  Attendance
count  10.000000  11.000000   10.000000
mean   20.400000  81.181818   82.000000
std     8.181279  11.889644   11.333333
min    10.000000  60.000000   65.000000
25%    18.000000  73.500000   72.750000
50%    19.000000  81.000000   82.500000
75%    20.000000  90.500000   91.000000
max    42.000000  96.000000   98.000000

In [25]:
df['Student_profile'].value_counts()

Student_profile
Workable      4
Good          4
Brilliant!    2
Loser         1
Name: count, dtype: int64

In [29]:
df['Attendance'].max()

np.float64(98.0)

In [31]:
hai = df['Attendance'] == 98
df[hai]

    Name   Age    City  Marks  Attendance age_group marks_band Student_profile
6  Priya  20.0  Indore     95        98.0     Adult       High            Good

In [35]:
df['Age'].sort_values()

9     10.0
5     17.0
7     18.0
3     18.0
4     19.0
0     19.0
6     20.0
2     20.0
10    21.0
8     42.0
1      NaN
Name: Age, dtype: float64

In [38]:
df.loc[9]

Name                  Vikas
Age                    10.0
City                    NaN
Marks                    73
Attendance             75.0
age_group              Teen
marks_band           Medium
Student_profile    Workable
Name: 9, dtype: object

In [74]:
df['Age'].isnull().value_counts()

Age
False    10
True      1
Name: count, dtype: int64

In [78]:
df['Age'].min()

np.float64(10.0)

In [79]:
df.isnull().sum()

Name               0
Age                1
City               1
Marks              0
Attendance         1
age_group          1
marks_band         0
Student_profile    0
dtype: int64

In [85]:
df['Age'].fillna(df['Age'].median())

0     19.0
1     19.0
2     20.0
3     18.0
4     19.0
5     17.0
6     20.0
7     18.0
8     42.0
9     10.0
10    21.0
Name: Age, dtype: float64

In [198]:
df

,Name,Age,City,Marks,Attendance,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,Teen,High,Brilliant!
1,Aman,NaN,Indore,78,85.0,NaN,Medium,Workable
2,Riya,20.0,Bhopal,92,95.0,Adult,High,Good
3,Kunal,18.0,Indore,67,80.0,Teen,Medium,Workable
4,Sneha,19.0,Ujjain,88,NaN,Teen,High,Brilliant!
5,Arjun,17.0,Bhopal,74,70.0,Teen,Medium,Workable
6,Priya,20.0,Indore,95,98.0,Adult,High,Good
7,Rohit,18.0,Ujjain,60,65.0,Teen,Low,Loser
8,Neha,42.0,Bhopal,81,88.0,Adult,High,Good
9,Vikas,10.0,NaN,73,75.0,Teen,Medium,Workable
10,Anjali,21.0,Ujjain,89,92.0,Adult,High,Good

In [245]:
grp = df.groupby('City')['Marks']

In [246]:
df.groupby('City')['Marks'].min()

City
Bhopal    74
Indore    67
Mhow      96
Ujjain    60
Name: Marks, dtype: int64

In [249]:
grp.get_group('Ujjain').sort_values()

7     60
4     88
10    89
Name: Marks, dtype: int64

In [240]:
df.loc[7]

Name                Rohit
Age                  18.0
City               Ujjain
Marks                  60
Attendance           65.0
age_group            Teen
marks_band            Low
Student_profile     Loser
Name: 7, dtype: object

In [242]:
df.groupby('City')['Name'].count()

City
Bhopal    3
Indore    3
Mhow      1
Ujjain    3
Name: Name, dtype: int64

In [250]:
df.groupby('City')['Marks'].describe()

        count       mean        std   min   25%   50%   75%   max
City
Bhopal    3.0  82.333333   9.073772  74.0  77.5  81.0  86.5  92.0
Indore    3.0  80.000000  14.106736  67.0  72.5  78.0  86.5  95.0
Mhow      1.0  96.000000        NaN  96.0  96.0  96.0  96.0  96.0
Ujjain    3.0  79.000000  16.462078  60.0  74.0  88.0  88.5  89.0

In [14]:
df.groupby('City')['marks_band'].value_counts()

City    marks_band
Bhopal  High          2
        Medium        1
Indore  Medium        2
        High          1
Mhow    High          1
Ujjain  High          2
        Low           1
Name: count, dtype: int64

In [9]:
df.describe()

             Age      Marks  Attendance
count  10.000000  11.000000   10.000000
mean   20.400000  81.181818   82.000000
std     8.181279  11.889644   11.333333
min    10.000000  60.000000   65.000000
25%    18.000000  73.500000   72.750000
50%    19.000000  81.000000   82.500000
75%    20.000000  90.500000   91.000000
max    42.000000  96.000000   98.000000

In [17]:
df

,Name,Age,City,Marks,Attendance,Unnamed: 5,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
1,Atharv,19.0,Mhow,96,72.0,NaN,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,NaN,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,NaN,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,NaN,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,NaN,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,NaN,Teen,Low,Loser
10,Neha,42.0,Bhopal,81,88.0,NaN,Adult,High,Good
11,Vikas,10.0,NaN,73,75.0,NaN,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,NaN,Adult,High,Good

In [24]:
df.dropna(axis='columns', how='all', inplace=True)

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df['Marks'].sort_values(ascending=False)

0     96
7     95
3     92
12    89
5     88
8     81
2     78
6     74
11    73
4     67
9     60
Name: Marks, dtype: int64

In [30]:
df['']

,Name,Age,City,Marks,Attendance,age_group,marks_band,Student_profile
0,Atharv,19.0,Mhow,96,72.0,Teen,High,Brilliant!
2,Aman,NaN,Indore,78,85.0,NaN,Medium,Workable
3,Riya,20.0,Bhopal,92,95.0,Adult,High,Good
4,Kunal,18.0,Indore,67,80.0,Teen,Medium,Workable
5,Sneha,19.0,Ujjain,88,NaN,Teen,High,Brilliant!
6,Arjun,17.0,Bhopal,74,70.0,Teen,Medium,Workable
7,Priya,20.0,Indore,95,98.0,Adult,High,Good
8,Neha,42.0,Bhopal,81,88.0,Adult,High,Good
9,Rohit,18.0,Ujjain,60,65.0,Teen,Low,Loser
11,Vikas,10.0,NaN,73,75.0,Teen,Medium,Workable
12,Anjali,21.0,Ujjain,89,92.0,Adult,High,Good

In [5]:
import numpy as np

In [6]:
x = [2, 4, 5, 3, 6]
y = np.array(x)

In [7]:
print(y)
print(type(y))

[2 4 5 3 6]
<class 'numpy.ndarray'>

In [8]:
import numpy as np
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.isnull().sum()
df.shape

In [10]:
df.isnull().sum()

name           0
age            1
marks          2
study_hours    1
city           2
dtype: int64

In [11]:
df.shape

(18, 5)

In [41]:
cleandf = df.drop_duplicates()

In [43]:
cleandf.isnull().sum()

name           0
age            1
marks          0
study_hours    1
city           1
Performance    2
dtype: int64

In [44]:
cleandf = df[df["marks"].notnull()]

In [45]:
df["marks"].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
Name: marks, dtype: bool

In [51]:
cleandf.loc[cleandf['marks'] >= 80, 'Performance'] = 'High'
cleandf.loc[(cleandf['marks'] < 80) | (cleandf['marks'] >= 60), 'Performance'] = 'Medium'
cleandf.loc[cleandf['marks'] < 60, 'Performance'] = 'Low'
cleandf['marks'] = cleandf['marks'].fillna(cleandf['marks'].median())

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('student_performance.csv')
df.isnull().sum()

name           0
age            1
marks          2
study_hours    1
city           2
dtype: int64

In [2]:
cleandf = df.drop_duplicates()

In [3]:
cleandf['marks'] = cleandf['marks'].fillna(cleandf['marks'].median())

In [4]:
cleandf.loc[cleandf['marks'] > 80, 'Performance'] = 'High'
cleandf.loc[(cleandf['marks'] < 80) & (cleandf['marks'] > 60), 'Performance'] = 'Medium'
cleandf.loc[cleandf['marks'] < 60, 'Performance'] = 'Low'

In [5]:
cleandf['age'] = cleandf['age'].fillna(cleandf['age'].median())
cleandf['study_hours'] = cleandf['study_hours'].fillna(cleandf['study_hours'].median())

In [6]:
cleandf = cleandf.dropna(subset=['city'])

In [7]:
cleandf.reset_index(inplace = True)

In [8]:
cleandf.loc[cleandf['study_hours'] >= 5, 'Study Category'] = 'Serious'
cleandf.loc[cleandf['study_hours'] < 5, 'Study Category'] = 'Casual'

In [9]:
cleandf.loc[cleandf['Performance'].str.contains('High') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Good'
cleandf.loc[cleandf['Performance'].str.contains('High') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Brilliant'
cleandf.loc[cleandf['Performance'].str.contains('Low') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Gotta focus'
cleandf.loc[cleandf['Performance'].str.contains('Low') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Study Beta'
cleandf.loc[cleandf['Performance'].str.contains('Medium') & cleandf['Study Category'].str.contains('Serious'), 'Overall'] = 'Improve focus'
cleandf.loc[cleandf['Performance'].str.contains('Medium') & cleandf['Study Category'].str.contains('Casual'), 'Overall'] = 'Study more'

In [10]:
cleandf

,index,name,age,marks,study_hours,city,Performance,Study Category,Overall
0,0,Aarav Sharma,19.0,85.0,6.0,Delhi,High,Serious,Good
1,1,Priya Singh,20.0,92.0,8.0,Mumbai,High,Serious,Good
2,3,Sneha Patel,21.0,68.0,5.0,Bangalore,Medium,Serious,Improve focus
3,4,Vikram Das,19.0,76.5,3.0,Kolkata,Medium,Casual,Study more
4,5,Ananya Iyer,20.0,88.0,7.0,Chennai,High,Serious,Good
5,7,Kabir Khan,22.0,95.0,9.0,Delhi,High,Serious,Good
6,8,Meera Nair,19.0,55.0,5.0,Pune,Low,Serious,Gotta focus
7,9,Arjun Reddy,20.0,79.0,6.0,Hyderabad,Medium,Serious,Improve focus
8,10,Ishan Verma,19.0,82.0,5.0,Ahmedabad,High,Serious,Good
9,11,Kavita Rao,21.0,45.0,2.0,Bangalore,Low,Casual,Study Beta
10,12,Sahil Mehta,19.0,90.0,7.0,Mumbai,High,Serious,Good
11,14,Riya Das,18.0,62.0,4.0,Kolkata,Medium,Casual,Study more
12,15,Amit Shah,20.0,76.5,6.0,Delhi,Medium,Serious,Improve focus
13,16,Pooja Joshi,19.0,71.0,3.0,Pune,Medium,Casual,Study more
14,17,Vikram Das,19.0,40.0,3.0,Kolkata,Low,Casual,Study Beta

In [11]:
cleandf.groupby('city')['marks'].mean()

city
Ahmedabad    82.0
Bangalore    56.5
Chennai      88.0
Delhi        85.5
Hyderabad    79.0
Kolkata      59.5
Mumbai       91.0
Pune         63.0
Name: marks, dtype: float64

In [12]:
cleandf.groupby('Performance')['marks'].mean()

Performance
High      88.666667
Low       46.666667
Medium    72.166667
Name: marks, dtype: float64

In [15]:
array = cleandf['marks'].astype(float).to_numpy()

In [16]:
print(array)

[85.  92.  68.  76.5 88.  95.  55.  79.  82.  45.  90.  62.  76.5 71.
 40. ]

In [17]:
array.mean()

np.float64(73.66666666666667)

In [18]:
array.max()

np.float64(95.0)

In [19]:
array.min()

np.float64(40.0)

In [20]:
gudarray = 1/array.max() * array

In [21]:
print(gudarray)

[0.89473684 0.96842105 0.71578947 0.80526316 0.92631579 1.
 0.57894737 0.83157895 0.86315789 0.47368421 0.94736842 0.65263158
 0.80526316 0.74736842 0.42105263]

In [32]:
cleandf['marks'].sort_values(ascending = False).head()

5     95.0
1     92.0
10    90.0
4     88.0
0     85.0
Name: marks, dtype: float64